import { neon } from "@neondatabase/serverless";
import { config } from "../config";

export async function runMigrations() {
  const sql = neon(config.databaseUrl);

  await sql`
    CREATE TABLE IF NOT EXISTS users (
      id SERIAL PRIMARY KEY,
      username TEXT NOT NULL UNIQUE,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      created_at TEXT NOT NULL DEFAULT now()
    )
  `;

  await sql`
    CREATE TABLE IF NOT EXISTS provider_id_cache (
      id SERIAL PRIMARY KEY,
      anilist_id INTEGER NOT NULL UNIQUE,
      provider TEXT NOT NULL DEFAULT 'gogoanime',
      provider_anime_id TEXT NOT NULL,
      updated_at TEXT NOT NULL DEFAULT now()
    )
  `;

  // Create watchlist without the old single-column unique on anime_id
  await sql`
    CREATE TABLE IF NOT EXISTS watchlist (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      anime_id INTEGER NOT NULL,
      anime_title TEXT NOT NULL,
      anime_cover TEXT,
      format TEXT,
      episodes INTEGER,
      score INTEGER,
      status TEXT,
      added_at TEXT NOT NULL DEFAULT now()
    )
  `;

  // Create watch_history without the old unique on (anime_id, episode_id)
  await sql`
    CREATE TABLE IF NOT EXISTS watch_history (
      id SERIAL PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      anime_id INTEGER NOT NULL,
      episode_id TEXT NOT NULL,
      episode_number INTEGER NOT NULL,
      progress_seconds REAL NOT NULL DEFAULT 0,
      duration_seconds REAL NOT NULL DEFAULT 0,
      anime_title TEXT NOT NULL,
      anime_cover TEXT,
      watched_at TEXT NOT NULL DEFAULT now()
    )
  `;

  // ── Idempotent alterations for existing deployments ─────────────────────────

  // Add user_id column to watchlist if it doesn't exist yet
  await sql`
    ALTER TABLE watchlist ADD COLUMN IF NOT EXISTS
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  `;

  // Add user_id column to watch_history if it doesn't exist yet
  await sql`
    ALTER TABLE watch_history ADD COLUMN IF NOT EXISTS
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
  `;

  // Drop old single-column unique constraints that conflict with per-user scoping.
  // The old names are auto-generated by PostgreSQL from the original CREATE TABLE.
  await sql`
    ALTER TABLE watchlist DROP CONSTRAINT IF EXISTS watchlist_anime_id_key
  `;

  await sql`
    ALTER TABLE watch_history DROP CONSTRAINT IF EXISTS watch_history_anime_id_episode_id_key
  `;

  // Add new per-user unique constraints if they don't exist
  await sql`
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'watchlist_user_id_anime_id_key'
      ) THEN
        ALTER TABLE watchlist ADD CONSTRAINT watchlist_user_id_anime_id_key
          UNIQUE (user_id, anime_id);
      END IF;
    END $$
  `;

  await sql`
    DO $$ BEGIN
      IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'watch_history_user_id_anime_id_episode_id_key'
      ) THEN
        ALTER TABLE watch_history ADD CONSTRAINT watch_history_user_id_anime_id_episode_id_key
          UNIQUE (user_id, anime_id, episode_id);
      END IF;
    END $$
  `;
}
